// Cash order Actions 
export const ADD_PRODUCT = "[CASH ORDER] ADD PRODUCT TO CART"
export const REMOVE_PRODUCT = "[CASH ORDER] REMOVE PRODUCT FROM CART"
export const PRODUCTS_BEING_FETCHED = "[CASH ORDER] PRODUCTS BEING FETCHED"
export const PRODUCTS_FETCH_SUCCESS = "[CASH ORDER] PRODUCTS FETCH SUCCESS"
export const PRODUCTS_FETCH_ERROR = "[CASH ORDER] PRODUCTS FETCH ERROR"
export const COMPLETE_ORDER = "[CASH ORDER] COMPLETE ORDER"
export const SUBMIT_ORDER = "[CASH ORDER] SUBMIT ORDER"
export const EMPTY_CART = "[CASH ORDER] CLEAR CART"
export const INCREASE_QUANTITY = "[CASH ORDER] INCREASE PRODUCT QUANTITY"
export const DECREASE_QUANTITY = "[CASH ORDER] DECREASE PRODUCT QUANTITY"
export const CALCULATE_SUMMARY = "[CASH ORDER] PERFORM CALCULATIONS FOR SUMMARY"
export const SUBMIT_ORDER_ERROR = "[CASH ORDER] ORDER SUBMISSION ERROR OCCURED"
export const CATEGORY_CHANGED = "[CASH ORDER] PRODUCTS CATEGORY CHANGED"
export const SEARCH_TEXT = "[CASH ORDER] USER SEARCHED FOR PRODUCT"
export const FILTERS_CHANGED = "[CASH ORDER] CASH ORDER FILTERS CHANGED"
export const CHANGE_RECIEVED_AMOUNT = "[CASH ORDER] PRODUCT RECIEVED AMOUNT CHANGED";
export const CHANGE_ORDER_TYPE = "[CASH ORDER] ORDER TYPE CHANGED";
export const CHANGE_CLIENT = "[CASH ORDER] SELECTED CLIENT CHANGED";
export const CHANGE_ORDER_MARKUP = "[CASH ORDER] MARKUP CHANGED ORDER";
export const CHANGE_ORDER_DISCOUNT = "[CASH ORDER] DISCOUNT CHANGED ORDER";
export const CHANGE_GUARANTOR1 = "[CASH ORDER] GUARANTOR ONE CHANGED";
export const CHANGE_GUARANTOR = "[CASH ORDER] GUARANTOR CHANGED";
export const CHANGE_GUARANTOR2 = "[CASH ORDER] GUARANTOR TWO CHANGED";
export const SET_CURRENT_PRODUCT = "[CASH ORDER] SET CURRENT PRODUCT";
export const SELECT_INVENTORY_ITEMS = "[CASH ORDER] SELECT INVENTORY";
export const SELECT_ORDER = "[CASH ORDER] SELECT ORDER";



//Preloader for whole site
export const HIDE_SPINNER = "[STORE] HIDE PRE-LOADER"
export const SHOW_SPINNER = "[STORE] SHOW PRE-LOADER"


//Print Actions
export const PRINT_CASH_INVOICE = "[CASH_ORDER_PRINT] PRINT INITIATED CASH-ORDER INVOICE"
export const PRINT_FETCH_DATA = "[CASH_ORDER_PRINT] FETCHING CASH-ORDER INVOICE DATA"
export const PRINT_DATA_FETCHED = "[CASH_ORDER_PRINT] FETCHED CASH-ORDER INVOICE DATA"
export const PRINTED_CASH_INVOICE = "[CASH_ORDER_PRINT] PRINTED CASH-ORDER INVOICE DATA"
export const PRINT_DATA_FETCH_ERROR = "[CASH_ORDER_PRINT] FETCHING CASH-ORDER INVOICE DATA ERROR"

//Dashboard Actions
export const LOAD_DASHBOARD_CARD_STATS = "[DASHBOARD] FETCH DASHBOARD CARD STATS"
export const LOADED_DASHBOARD_CARD_STATS = "[DASHBOARD] DASHBOARD CARD STATS FETCHED "

export const LOAD_DASHBOARD_RECENT_ORDERS = "[DASHBOARD] FETCH DASHBOARD RECENT ORDERS"
export const LOADED_DASHBOARD_RECENT_ORDERS = "[DASHBOARD] DASHBOARD RECENT ORDERS FETCHED"
export const CHANGE_DASHBOARD_FILTERS_RECENT_ORDERS = "[DASHBOARD] DASHBOARD RECENT ORDERS FILTERS CHANGED"

export const LOAD_DASHBOARD_SALES = "[DASHBOARD] FETCH DASHBOARD SALES"
export const LOADED_DASHBOARD_SALES = "[DASHBOARD] DASHBOARD SALES FETCHED"

export const LOAD_DASHBOARD_ORDERS_COUNT = "[DASHBOARD] FETCH DASHBOARD ORDERS COUNT"
export const LOADED_DASHBOARD_ORDERS_COUNT = "[DASHBOARD] DASHBOARD ORDERS COUNT FETCHED"

export const LOAD_DASHBOARD_CATEGORIES = "[DASHBOARD] FETCH DASHBOARD CATEGORIES"
export const LOADED_DASHBOARD_CATEGORIES = "[DASHBOARD] DASHBOARD CATEGORIES FETCHED"

export const LOAD_DASHBOARD_LOGS = "[DASHBOARD] FETCH DASHBOARD LOGS"
export const LOADED_DASHBOARD_LOGS = "[DASHBOARD] DASHBOARD LOGS FETCHED"
export const CHANGE_DASHBOARD_FILTERS_LOGS = "[DASHBOARD] DASHBOARD LOGS FILTERS CHANGED"

export const LOAD_DASHBOARD_PENDING_PAYMENTS = "[DASHBOARD] FETCH DASHBOARD PENDING PAYMENTS"
export const LOADED_DASHBOARD_PENDING_PAYMENTS = "[DASHBOARD] DASHBOARD PENDING PAYMENTS FETCHED"
export const CHANGE_DASHBOARD_FILTERS_PENDING_PAYMENTS = "[DASHBOARD] DASHBOARD PENDING PAYMENTS FILTER CHANGE"

export const LOAD_DASHBOARD_BEST_SELLERS = "[DASHBOARD] FETCH DASHBOARD BEST SELLERS"
export const LOADED_DASHBOARD_BEST_SELLERS = "[DASHBOARD] DASHBOARD BEST SELLERS FETCHED"
export const CHANGE_DASHBOARD_FILTERS_BEST_SELLERS = "[DASHBOARD] DASHBOARD BEST SELLERS FILTERS CHANGED"

export const LOAD_DASHBOARD_SUMMARY_STATS = "[DASHBOARD] FETCH DASHBOARD SUMMARY STATS"
export const LOADED_DASHBOARD_SUMMARY_STATS = "[DASHBOARD] DASHBOARD SUMMARY STATS FETCHED"

export const LOAD_DASHBOARD_PRODUCTS = "[DASHBOARD] FETCH DASHBOARD PRODUCTS"
export const LOADED_DASHBOARD_PRODUCTS = "[DASHBOARD] DASHBOARD PRODUCTS FETCHED"

export const LOAD_DASHBOARD_CARD_STATS_SORTABLE = "[DASHBOARD] FETCH DASHBOARD CARD STATS SORTABLE"
export const LOADED_DASHBOARD_CARD_STATS_SORTABLE = "[DASHBOARD] CARD DASHBOARD STATS SORTABLE FETCHED"

export const LOAD_DASHBOARD_OTHER_STATS_LEFT = "[DASHBOARD] FETCH DASHBOARD OTHER STATS"
export const LOADED_DASHBOARD_OTHER_STATS_LEFT = "[DASHBOARD] OTHER DASHBOARD STATS FETCHED"
export const LOADED_DASHBOARD_DATA_FETCH_ERROR = "[DASHBOARD] OTHER DASHBOARD STATS ERROR OCCURED"

//Inventory Form Actions
export const INVENTORY_FORM_ADD_ITEM = "[INVENTORY_FORM] ADD ITEM TO INVENTOY FORM"
export const INVENTORY_FORM_RESET = "[INVENTORY_FORM] RESET INVENTOY FORM"
export const INVENTORY_FORM_REMOVE_ITEM = "[INVENTORY_FORM] REMOVE ITEM FROM INVENTORY FORM"
export const INVENTORY_FORM_SUBMIT = "[INVENTORY_FORM] INVENTORY FORM SUBMITTED"
export const INVENTORY_FORM_CHANGE_QUANTITY = "[INVENTORY_FORM] PRODUCT QUANTITY CHANGED IN INVENTORY FORM"
export const INVENTORY_FORM_BARCODE_SCANNED = "[INVENTORY_FORM] A BARCODE SCANNED"
export const INVENTORY_FORM_SEARCH_ITEM = "[INVENTORY_FORM] SEARCH FOR PRODUCT"
export const INVENTORY_FORM_ITEMS_FETCHED = "[INVENTORY_FORM] RESULTS ARE FETCHED FROM BACKEND"
export const INVENTORY_FORM_SEARCH_SELECT_ITEM = "[INVENTORY_FORM] SELECT ITEM FROM SEARCH"
export const INVENTORY_FORM_PRODUCTS_ADD = "[INVENTORY_FORM] INSERT MULTIPLE PRODUCTS";
export const INVENTORY_FORM_BARCODE_REMOVE = "[INVENTORY_FORM] REMOVE BARCODE OF PRODUCT";
export const INVENTORY_FORM_BARCODE_ADD = "[INVENTORY_FORM] ADD BARCODE OF PRODUCT";

export const INVENTORY_FORM_KEY_PRESS = "[INVENTORY_FORM] KEYBOARD KEY PRESS";
export const INVENTORY_FORM_LEFT_ARROW = "[INVENTORY_FORM] LEFT ARROW KEY PRESS";
export const INVENTORY_FORM_DOWN_ARROW = "[INVENTORY_FORM] DOWN ARROW KEY PRESS";
export const INVENTORY_FORM_UP_ARROW = "[INVENTORY_FORM] UP ARROW KEY PRESS";
export const INVENTORY_FORM_RIGHT_ARROW = "[INVENTORY_FORM] RIGHT ARROW KEY PRESS";
export const INVENTORY_FORM_ITEM_SELECTED = "[INVENTORY_FORM] CHANGE ITEM SELECTED";
export const INVENTORY_FORM_PRODUCT_CHANGE = "[INVENTORY_FORM] CHANGE PRODUCT";

export const INVENTORY_FORM_CHANGE_BARCODE = "[INVENTORY_FORM] CHANGE BARCODE OF PRODUCT";
export const INVENTORY_FORM_CHANGE_EAN = "[INVENTORY_FORM] CHANGE EAN OF PRODUCT";
export const LOAD_PRODUCTS = "LOAD PODUCTS LIST"
export const PRODUCTS_LOADED = "PRODUCTS LIST LOADED"
export const PRODUCTS_LOAD_ERROR = "PRODUCTS LOAD ERROR"
